data:
  data_dir: "cornell movie-dialogs corpus"
  min_length: 1
  max_length: 10
  validation_split: 0.2
  train_file: "data/train.txt"
  val_file: "data/val.txt"
model:
  encoder_embedding_size: 256
  decoder_embedding_size: 256
  hidden_size: 512
  num_layers: 2
  dropout: 0.5
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 100
  device: cuda
